version: '3.1'

services:
  api_crypt:
    image: "registry.iron-labs.de:5000/api/crypt:3.0.0"
    user: "node"
    working_dir: /home/node/app
    restart: on-failure
    deploy:
      labels:
        traefik.enable: "false"
    ports:
      - 7001:7001
    networks:
      - backend
      - redis
      - mongo
    command: "npm run staging"

networks:
  backend:
    external: true
  redis:
    external: true
  mongo:
    external: true
