version: '3.1'

services:
  api_crypt:
    image: "deviant.code:5000/api/crypt:1.1.0"
    user: "node"
    working_dir: /home/node/app
    restart: on-failure
    deploy:
      labels:
        traefik.enable: "false"
    ports:
      - 7001:7001
    networks:
      - backend
    command: "npm run dev"

networks:
  backend:
    external: true